# docker-compose.yml
version: "3.8"
services:
  #my-app:
  # image: dockerysf/my-app:1.0
  #  ports:
  #   - 3000:3000
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # docker exec -it mongodb sh
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    links:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
volumes:
  mongo-data:
    driver: local


